### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by CoolMan119** [Poeschl/autocomplete-computercraft#1]
[Enter steps to reproduce:]

1. All i did was start up Atom
2. and it happened

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-computercraft](https://github.com/poeschl/autocomplete-computercraft) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\minecraft\.atom\packages\autocomplete-computercraft\lib\provider.coffee:46

TypeError: Cannot read property 'length' of undefined
    at Object.getPossibleClass (/packages/autocomplete-computercraft/lib/provider.coffee:46:13)
    at Object.getSuggestions (/packages/autocomplete-computercraft/lib/provider.coffee:9:10)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
undefined -0:36.9.0 core:backspace (input.hidden-input)
  2x -0:01.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-modern-syntax 0.0.0 
autoclose-html 0.23.0 
autocomplete-computercraft 1.0.0 
climate-syntax 5.0.0 
climate-ui 4.5.1 
collaby 0.2.7 
language-batch 0.4.0 
language-computercraft 0.2.1 
language-lua 0.9.11 
material-syntax 0.0.0 
minimap 4.26.8 
monokai 0.18.0 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
now-syntax 0.2.4 
nucleus-dark-ui 0.10.22 
Remote-FTP 0.10.5 
todo 0.6.0 
```

**Comment by Poeschl** [comment]
Will look at it, at next weekend

**Comment by Poeschl** [comment]
Couldn't reproduce the crash. Did you changed something in the package folder? Or did you try to reinstall the plugin?

**Comment by Poeschl** [comment]
Closing this issue, due no activity for more than a year.
